version: '3.7'

services:
  mariadb:
    image: mariadb:latest
    container_name: my-mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ist-hub
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
